### PR TITLE
Submodule integration for piscem

### PR DESCRIPTION
**Pull request by jermp**

### CODE REVIEW

**Review by jermp — COMMENTED** [review]
Hi @rob-p and @NPSDC 

I've incorporated the support for CUTTLEFISH input and the other things in the `dev` branch (see latest commit). The only thing missing is the alternative streaming query code.
Do you confirm the following
https://github.com/COMBINE-lab/piscem-cpp/blob/c5f1fe7cd7decb6012804ebef9dfe079502ac3b6/include/query/streaming_query_canonical_parsing.hpp
is the version I should look at?

**Comment by NPSDC** [comment]
Hi @jermp .
Thank you so much for being so prompt in fixing the merge. The streaming query code is the same as the current sshash. Only thing to be added is the `reset_state` function.
https://github.com/COMBINE-lab/piscem-cpp/blob/c5f1fe7cd7decb6012804ebef9dfe079502ac3b6/include/query/streaming_query_canonical_parsing.hpp#L46

**Comment by jermp** [comment]
@NPSDC @rob-p   mmh...it's not the same as the version committed here in this branch
and in the `submodule-integration-for-piscem`, no?
It has some additional attributes and the additional function.
Also, the version we are looking at in piscem has a different logic for the `lookup_advanced` method.

Shall we also merge those changes?

**Comment by rob-p** [comment]
Hi @jermp and @NPSDC,

  So we are requesting the changes in the submodule-integration-for-piscem branch (i.e. that is the addition of the `reset_state` function and any new variables it touches).

  However, what exists upstream in `piscem` now is needlessly complex, as it too tightly couples the streaming iterator and the k-mer iterator over the read.  We have a new design that loosens the coupling by adding an adaptor to the streaming iterator to reset the state whenever the next k-mer queried is not at the position directly following the previous query.  This achieves the same thing while not pushing too much extra complication into the streaming iterator in sshash upstream. Let me know if I've forgotten anything @NPSDC.

--Rob

**Comment by NPSDC** [comment]
hi @jermp and @rob-p ,
So we are only requesting merge w.r.t sshash `submodule-integration-for-piscem` branch with the sshash `dev` branch. Nothing has to be done w.r.t `piscem-cpp`, since the piscem-cpp currently uses that sshash branch as a submodule, and accordingly its code has been updated (`dev-atac`). This branch for sshash adds the `reset_state` function in the `streaming_canonical_query_file`. Otherwise, this file has not been tampered with from the initial merge that was requested here
https://github.com/jermp/sshash/pull/47

**Comment by jermp** [comment]
Hi @rob-p and @NPSDC, and thanks for confirming!
As of 9e48d6bac2c84599ced98b9e4a9de1870ccc0ff1, I've added the `reset_state` method to both the canonical and regular streaming query. (Actually, I plan to revisit that code/logic at some point.)

The dev branch now should be ready. Can you try to see if it works well for piscem?

Thanks!

**Comment by NPSDC** [comment]
thanks @jermp . I am currently using the `submodule-integration-for-piscem` branch and doing some other testing. I will test the `dev` branch for piscem soon.

**Comment by jermp** [comment]
@NPSDC, thank you very much. Let me know!

**Pull request closed without merging**
