### PR TITLE
Partitioned phf

### PR DESCRIPTION
**Pull request by rickbeeloo**
I think we can already add this. 

The lookups were tested with https://github.com/rickbeeloo/UniqueMers, with `2^32` unique 17-mer lookup being correct according to the sshash `--check` (`UniqueMers kmers.fasta 17 4294967296 0`). 

I just added "tail" to the linked repo to add random sequences after each kmer allowing for the navigational queries to be tested, but instead of re-running sshash again for this I think we can better do Fulgor immediately.

### CODE REVIEW

**Review by jermp — CHANGES_REQUESTED** [review]
For simplicity, I would just default everything to `uint64_t`.
I agree that it should probably never exceed 2^32 nucleotides, but what's the advantage from the code perspective? None, so just use uint64_t is cleaner and safer.
Thanks!

**Comment by rickbeeloo** [comment]
Hey @jermp, what did you actually mean? The lookup struct right (the contig size)?

**Comment by jermp** [comment]
> Hey @jermp, what did you actually mean? The lookup struct right (the contig size)?

Yes, I would default everything to uint64_t.

**Comment by rickbeeloo** [comment]
There we go, everything to `uint_64`:
- Added `msb_uint64`, removed `msb` (uint32)
- Removed the constant `invalid_uint32` mainly cause Fulgor [reads these from sshash ](https://github.com/search?q=repo%3Ajermp%2Ffulgor+sshash%3A%3Aconstants%3A%3Ainvalid_uint32&type=code). I just read the `uint64` constant in my branch, but to be sure output from this branch isn't accidently verified using the `uint32` constant.
- The only thing we still have `uint32` is the crc for the gzips

Let me know :)

**Comment by jermp** [comment]
Sorry for the confusion but in my comment I was referring to the `uint32_t` inside the `lookup_result` struct.
The other place where uint32_t is used are just fine.
So I'm gonna close this pull request and make the change myself to avoid conflicts.
Thanks!

**Comment by jermp** [comment]
Date as of https://github.com/jermp/sshash/commit/fbe00d9f1ca4fa875177deba11a7e9b9e5c2b71a.

**Pull request closed without merging**
